sudo: required
language: node_js
node_js:
  - $NODE_VERSION

#cache:
#  directories:
#    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
before_install:
  # native dependencies
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo apt-get update -qq;
      sudo apt-get install -qq libxml2-dev;
      sudo apt-get install -qq libappindicator1;
    fi
install:
  - git config --global core.autocrlf input
  - git reset --hard HEAD
  - npm run sencha:clean
  - git clone https://github.com/saenzramiro/rambox-build.git $TRAVIS_BUILD_DIR/build/production/Rambox/
  - npm install
  - npm uninstall electron-prebuilt
  - npm i electron-prebuilt@$ELECTRON
  - npm --prefix $TRAVIS_BUILD_DIR/build/production/Rambox/ install $TRAVIS_BUILD_DIR/build/production/Rambox/
script:
  - echo $TRAVIS_OS_NAME
  - node --version
  - npm --version
  - npm run build:$TRAVIS_OS_NAME
deploy:
  provider: releases
  api_key:
    secure: F7z4j9xzhpVyfovrf33jbVdW9dwgpIgbn85dxe8y/kZbQ9sAVU8LzoBZ3PlfeXmoV5CnSUa5j/fe8BmPKiG31kgAH7cktsCOgyOLggO1Sy+vnx7RQwwE/jzb7PzEqI2BP6TG/eOfylBxGBInWeaoSRfK3IRAvLHvvxY1eL4Wq/KRaanzMvh+JdCaStIKJSnI/rc9noI7vtOtgHot+F162s1G1k5/UcdbsfXWzotMVsonhlGgB/Jz9srnJpMpxYxaknR8UFPVRzOM5UzzMo64hXRUDnCFlYcTHcSAkvgKHI0SIPIS3kOdvgrYGavPLK2CAteQk7Dy1lHnEixmKPxG7eVAFwleUo8ePR82WXFkv5gacCvcrGrRLQ9nC/ygeMVgC5XxcHq3ykkcrstu5yjC1yEYFs23gA1Z4DIctwq1diyO72/FNxghV5ckN5WtJQs1QTT+Ec2NjLrWgFYuaEHYgAGopzTPN8gT9fyIv/lAq1S/l4P/z3EDS42UL+UTM77gyXSYShCKneDnFC34ATlYNDhJFRzLZ6qJG5UlOwrfXxUYeGUpQZlV41jg+VFWmPDAeQTMjGP5fRA3w1hFobBotBVyrtbcovTb4TFVTKJWOC/0wyiwku7YTY/nqMU/hR4IluTyRh9Z4NMn5xT5UW63OZd4DJvE573JxmJmnPc0fbo=
  file:
    - "dist/rambox-0.4.2-ia32.zip"
    - "dist/rambox-0.4.2.zip"
    - "dist/rambox-0.4.2-ia32.deb"
    - "dist/rambox-0.4.2.deb"
    - "dist/rambox-0.4.2-ia32.tar.gz"
    - "dist/rambox-0.4.2.tar.gz"
    - "dist/Rambox-0.4.2-ia32.AppImage"
    - "dist/Rambox-0.4.2.AppImage"
    - "dist/mac/Rambox-0.4.2-mac.zip"
    - "dist/mac/Rambox-0.4.2.dmg"
  skip_cleanup: true
  on:
    repo: saenzramiro/rambox
    tags: true
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0f214eb0d0017d3c5561
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
