environment:
  matrix:
    - nodejs_version: '14.16.1'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_non_tags: true
init:
  - cmd: git config --global core.autocrlf input
  - cmd: node --version
  - cmd: npm --version
install:
  - ps: Update-NodeJsInstallation $env:nodejs_version x64
  - cmd: >-
      git clone https://github.com/saenzramiro/rambox-build.git %APPVEYOR_BUILD_FOLDER%\build\production\Rambox\

      cd %APPVEYOR_BUILD_FOLDER%\build\production\Rambox\

      npm install
build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\build\production\Rambox\
  - cmd: npm run build:win
test: off
